version: "3.9"

services:
    mongoDB:
        image: mongo
        ports:
            - '27017:27017'

    server:
        build: .
        image: backend
        ports:
            - '3000:3000'
        links:
            - mongoDB
        environment: 
            - MONGO_URI_PROD=mongodb://mongoDB:27017/workflow
